# Generated by Django 4.1 on 2024-08-30 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0002_auto_20210213_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="mobile number error", regex="^\\+?1?\\d{9,15}$"
                    )
                ],
            ),
        ),
    ]
