# Generated by Django 4.1 on 2024-08-30 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0002_alter_patient_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile_number",
                        message="Mobile number must be 10 digits",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
