# Generated by Django 4.1 on 2024-08-30 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patient", "0004_alter_patient_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="mobile number error", regex="^\\+?1?\\d{9,15}$"
                    )
                ],
            ),
        ),
    ]
